controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - a1_c1
      - c2_a1
      - a2_c2
      - c3_a2
      - a3_c3
      - c4_a3
      - a4_c4
      - c5_a4
      - a5_c5
      - c6_a5
      - a6_c6
      - c7_a6
      - a7_c7
      - c8_a7
      - a8_c8
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - a8_c8
initial:  # Define initial robot poses.
  - group: arm
    pose: home