test13:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: home
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - c1_box
      - a1_c1
      - c2_a1
      - a2_c2
      - c3_a2
      - a3_c3
      - c4_a3
      - a4_c4
      - c5_a4
      - a5_c5
      - c6_a5
      - a6_c6
      - c7_a6
      - a7_c7
      - c8_a7
      - a8_c8
      - wh3_car
      - wh4_car
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []